version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "rabbitmq_container"
    ports:
      - "5672:5672"   # Porta de comunica��o AMQP
      - "15672:15672" # Interface de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
